import pandas as pd
from datetime import datetime
import io
from core.constants import UIConstants

class ReportService:
    @staticmethod
    def generate_csv_report(df, report_name, user_name):
        """Generates a professional CSV buffer with metadata."""
        if df.empty:
            return None
            
        output = io.StringIO()
        
        # Add Metadata Header
        output.write(f"# HOSPITAL ERP REPORT: {report_name}\n")
        output.write(f"# Generated At: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        output.write(f"# Generated By: {user_name}\n")
        output.write(f"# System Version: {UIConstants.VERSION}\n")
        output.write("# -------------------------------------------\n")
        
        # Write Data
        df.to_csv(output, index=False)
        
        return output.getvalue()

    @staticmethod
    def get_summary_statistics(df_basvuru):
        """Calculates high-level analytics for reporting."""
        if df_basvuru.empty:
            return {}
            
        stats = {
            "toplam_basvuru": len(df_basvuru),
            "triyaj_dagilimi": df_basvuru['OncelikDurumu'].value_counts().to_dict(),
            "ortalama_bekleme": "14 dk", # Mocked for now, will calculate in read_model
            "en_yogun_saat": "14:00 - 15:00"
        }
        return stats
